"""Public surface for harn-gibson."""

from harn_gibson.browser_capture import BrowserScreenshotResult, capture_scene_screenshot
from harn_gibson.catalog import CatalogEntry, VisualCatalog, default_visual_catalog
from harn_gibson.events import EventPhase, GibsonEvent, phase_for_event, summarize_event, to_jsonable
from harn_gibson.hooks import HookDecision, HookDispatcher, load_hook_module, result_for_harn
from harn_gibson.rendering import (
    ContextualSceneRenderer,
    DeterministicSceneRenderer,
    RendererContext,
    RendererContextBuilder,
    RendererContextConfig,
    RenderInputBatch,
    RenderPipeline,
    RenderPlan,
    RenderRequest,
    RenderStep,
    RenderSubmitResult,
    TimelineWindow,
)
from harn_gibson.replay import (
    ReplayExpectationError,
    ReplayExpectationResult,
    ReplayFileResult,
    ReplayResult,
    ReplayStepResult,
    ReplaySuiteResult,
    discover_replay_files,
    evaluate_replay_expectations,
    run_replay_data,
    run_replay_file,
    run_replay_suite,
)
from harn_gibson.routing import (
    EventRouter,
    EventRouteRule,
    RendererEventInterest,
    RouteDecision,
    StreamBinding,
    event_route_rules_from_value,
    renderer_event_interest_from_renderer,
    renderer_event_interest_from_value,
)
from harn_gibson.scene import (
    SceneAnimation,
    SceneEngine,
    SceneMutation,
    ScenePrimitive,
    SceneState,
    default_mutations_for_event,
    initial_scene,
    scene_update_payload,
)

__all__ = [
    "CatalogEntry",
    "BrowserScreenshotResult",
    "ContextualSceneRenderer",
    "EventPhase",
    "EventRouteRule",
    "GibsonEvent",
    "HookDecision",
    "HookDispatcher",
    "DeterministicSceneRenderer",
    "EventRouter",
    "RenderPipeline",
    "RenderInputBatch",
    "RenderPlan",
    "RenderRequest",
    "RenderStep",
    "RenderSubmitResult",
    "RendererContext",
    "RendererContextBuilder",
    "RendererContextConfig",
    "RendererEventInterest",
    "ReplayFileResult",
    "ReplayExpectationError",
    "ReplayExpectationResult",
    "ReplayResult",
    "ReplayStepResult",
    "ReplaySuiteResult",
    "RouteDecision",
    "SceneAnimation",
    "SceneEngine",
    "SceneMutation",
    "ScenePrimitive",
    "SceneState",
    "StreamBinding",
    "TimelineWindow",
    "VisualCatalog",
    "capture_scene_screenshot",
    "default_mutations_for_event",
    "default_visual_catalog",
    "discover_replay_files",
    "evaluate_replay_expectations",
    "event_route_rules_from_value",
    "initial_scene",
    "load_hook_module",
    "phase_for_event",
    "result_for_harn",
    "renderer_event_interest_from_renderer",
    "renderer_event_interest_from_value",
    "run_replay_data",
    "run_replay_file",
    "run_replay_suite",
    "scene_update_payload",
    "summarize_event",
    "to_jsonable",
]
